Check recode
EternalCodeTeam/EternalCheck pull request #30
Opened 2022-07-30 13:15 UTC by Osnixer

**Please describe the changes made by this PR and why they need to be merged:**

**Status:**

2022-07-30 13:38 UTC, vLuckyyy requested changes

2022-07-30 13:38 UTC, vLuckyyy commented on build.gradle.kts
> +tasks.withType<ShadowJar> {
# Zachęcam do zmiany tego 👇
```gradle
    exclude("org/intellij/lang/annotations/**")
    exclude("org/jetbrains/annotations/**")
    exclude("org/checkerframework/**")
    exclude("META-INF/**")
    exclude("javax/**")

    mergeServiceFiles()
    minimize()

    relocate("panda", "com.eternalcode.check.libs.org.panda")
    relocate("org.panda_lang", "com.eternalcode.check.libs.org.panda")
    relocate("net.dzikoysk", "com.eternalcode.check.libs.net.dzikoysk")
    relocate("dev.rollczi", "com.eternalcode.check.libs.dev.rollczi")
    relocate("org.bstats", "com.eternalcode.check.libs.org.bstats")
```

# Na to 👇
```gradle
    exclude("org/intellij/lang/annotations/**","org/jetbrains/annotations/**","org/checkerframework/**","META-INF/**","javax/**")

    mergeServiceFiles()
    minimize()

    val prefix = "com.eternalcode.check.libs"
    listOf(
        "panda",
        "org.panda_lang",
        "org.bstats",
        "net.dzikoysk",
        "dev.rollczi"
    ).forEach { pack ->
        relocate(pack, "$prefix.$pack")
    }
```

2022-07-30 13:38 UTC, vLuckyyy commented on src/main/java/com/eternalcode/check/command/implementation/CheckCommand.java
> +@Permission("EternalCheck.check")
EternalCheck -> eternalcheck.check

2022-07-30 13:38 UTC, vLuckyyy commented on src/main/java/com/eternalcode/check/command/implementation/CheckCommand.java
> +    public void executeReload(Player player) {
EternalCheck -> eternalcheck

2022-07-30 13:38 UTC, vLuckyyy commented on build.gradle.kts
> +    // paper lib, spigot api
nie używasz paperliba

```
paper lib, spigot api
```
👇
```
spigot api
```

2022-07-30 13:38 UTC, vLuckyyy commented on src/main/java/com/eternalcode/check/EternalCheck.java
> +    public static EternalCheck INSTANCE;
A to nie jest tak że "static final" piszę z dużych?

2022-07-30 14:09 UTC, Rollczi requested changes

2022-07-30 14:09 UTC, Rollczi commented on src/main/java/com/eternalcode/check/listener/PlayerQuitListener.java
>  public class PlayerQuitListener implements Listener {
LogoutPunishmentController?

2022-07-30 14:09 UTC, Rollczi commented on src/main/java/com/eternalcode/check/listener/PlayerMoveListener.java
>  public class PlayerMoveListener implements Listener {
CheckedPlayerMoveController?

2022-07-30 14:09 UTC, Rollczi commented on src/main/java/com/eternalcode/check/listener/PlayerCommandPreprocessListener.java
>  public class PlayerCommandPreprocessListener implements Listener {
CheckedPlayerCommandController

2022-07-30 14:09 UTC, Rollczi commented on src/main/java/com/eternalcode/check/listener/AsyncPlayerChatListener.java
>  public class AsyncPlayerChatListener implements Listener {
CheckedPlayerChatController

2022-07-30 14:09 UTC, Rollczi commented on src/main/java/com/eternalcode/check/user/UserTask.java
> +            UUID uniqueId = user.getUniqueId();
userUuid

2022-07-30 14:09 UTC, Rollczi commented on src/main/java/com/eternalcode/check/user/UserTask.java
> +    }
w https://github.com/EternalCodeTeam/EternalCore/blob/master/eternalcore/src/main/java/com/eternalcode/core/configuration/composer/DurationComposer.java masz fajny composer do tego
w formacie `1m` `1s` itd

2022-07-30 14:11 UTC, Rollczi requested changes

2022-07-30 14:11 UTC, Rollczi commented on src/main/java/com/eternalcode/check/command/implementation/AdmitCommand.java
> +        if (!userOptional.isPresent()) {
isEmpty?

2022-07-30 14:16 UTC, Osnixer commented on src/main/java/com/eternalcode/check/listener/AsyncPlayerChatListener.java
> +            if (!userOptional.isPresent()) {
Java 8

2022-07-30 14:18 UTC, Osnixer commented on src/main/java/com/eternalcode/check/command/implementation/AdmitCommand.java
> +        if (!userOptional.isPresent()) {
Java 8

2022-07-31 14:07 UTC, Rollczi requested changes

2022-07-31 14:07 UTC, Rollczi commented on src/main/java/com/eternalcode/check/config/implementation/DataConfig.java
> +        return Source.of(folder, "data"+ File.separator +"checkedusers.data");
spacja

2022-07-31 14:07 UTC, Rollczi commented on src/main/java/com/eternalcode/check/config/implementation/DataConfig.java
> +public class DataConfig implements ReloadableConfig {
CheckedUserDataConfig

2022-07-31 14:12 UTC, Rollczi approved these changes

2022-07-31 14:13 UTC, vLuckyyy approved these changes

2022-07-31 14:13 UTC, merged